import type { UsageTelemetryEvent } from "../core/usage/usage-event.js";
import type { ProviderRuntimeHealthSignal } from "../core/health/provider-runtime-health.js";

/** No fabricated uptime: empty buckets have no success percentage. */
export function activitySeries(events: readonly UsageTelemetryEvent[], signals: readonly ProviderRuntimeHealthSignal[], days: number, now = new Date()) {
  const key = (date: Date) => [date.getFullYear(), String(date.getMonth()+1).padStart(2,"0"), String(date.getDate()).padStart(2,"0")].join("-");
  const buckets = Array.from({ length: days }, (_, i) => { const date=new Date(now);date.setDate(date.getDate()-days+1+i);return { date:key(date), tokens:0, attempts:0, ok:0, failed:0 }; });
  const byDate = new Map(buckets.map(bucket => [bucket.date,bucket]));
  for (const event of events) { if(Date.parse(event.recordedAt)>now.valueOf())continue;const bucket=byDate.get(key(new Date(event.recordedAt)));if(bucket)bucket.tokens+=event.usage.totalTokens; }
  const observations = signals.length ? signals.map(signal=>({ at:signal.observedAt, ok:signal.outcome==="completed" })) : events.map(event=>({ at:event.recordedAt, ok:event.outcome==="completed" }));
  for(const signal of observations){if(Date.parse(signal.at)>now.valueOf())continue;const bucket=byDate.get(key(new Date(signal.at)));if(bucket){bucket.attempts++;if(signal.ok)bucket.ok++;else bucket.failed++;}}
  return buckets;
}

export const activityJavaScript = `
const activitySeries=${activitySeries.toString()};
let activityChart='tokens';
const activityExpanded=new Set();const activityPages={};const activitySearch={};
const healthColors={ONLINE:'#53ba91',DEGRADED:'#e1b05b',RATE_LIMITED:'#e1b05b',OFFLINE:'#e57079',AUTH_ERROR:'#e57079',INCOMPATIBLE:'#e57079',DISABLED:'#737983',UNKNOWN:'#9ba1aa'};
function svgNode(tag,attributes={}){const item=document.createElementNS('http://www.w3.org/2000/svg',tag);for(const [key,value] of Object.entries(attributes))item.setAttribute(key,String(value));return item}
function svgText(svg,x,y,label,extra={}){const text=svgNode('text',{x,y,fill:'#969daa','font-size':12,...extra});text.textContent=label;svg.append(text)}
function chartHint(shape,label){const title=svgNode('title');title.textContent=label;shape.append(title);shape.setAttribute('aria-label',label)}
function renderActivityDashboard(){
 const select=byId('activity-provider');if(!select)return;const old=select.value;select.replaceChildren(option('','Все провайдеры'));for(const profile of state.snapshot?.providers||[])select.append(option(profile.id,profile.displayName));select.value=providerById(old)?old:'';
 const id=select.value;const days=Number(byId('activity-range').value);const now=new Date();const cutoff=new Date(now);cutoff.setHours(0,0,0,0);cutoff.setDate(cutoff.getDate()-days+1);
 const events=(state.snapshot?.usageEvents||[]).filter(item=>(!id||item.providerId===id)&&Date.parse(item.recordedAt)>=cutoff.valueOf()&&Date.parse(item.recordedAt)<=now.valueOf());
 const signals=(state.snapshot?.health||[]).flatMap(record=>record.runtimeSignals||[]).filter(item=>(!id||item.providerId===id)&&Date.parse(item.observedAt)>=cutoff.valueOf()&&Date.parse(item.observedAt)<=now.valueOf());
 const series=activitySeries(events,signals,days,now);const rows=allModelRows().filter(row=>!id||row.providerId===id);const totals=series.reduce((out,b)=>({tokens:out.tokens+b.tokens,attempts:out.attempts+b.attempts,ok:out.ok+b.ok}),{tokens:0,attempts:0,ok:0});const costs={};for(const event of events)if(event.cost)costs[event.cost.currency]=(costs[event.cost.currency]||0)+event.cost.microunits;
 const metrics=byId('activity-metrics');metrics.replaceChildren(statCell('Попытки запросов',fmtNum(totals.attempts),'за '+days+' дней'),statCell('Успешность',totals.attempts?new Intl.NumberFormat('ru-RU',{maximumFractionDigits:1}).format(totals.ok/totals.attempts*100)+'%':'—','по сохранённым наблюдениям'),statCell('Токены',fmtNum(totals.tokens),'учтённые запросы'),statCell('Стоимость',Object.keys(costs).length?fmtCost(costs):'—','по настроенным тарифам'));
 const root=byId('activity-chart');root.replaceChildren();for(const button of document.querySelectorAll('[data-chart]')){button.classList.toggle('active',button.dataset.chart===activityChart);button.setAttribute('aria-selected',String(button.dataset.chart===activityChart))}
 if(activityChart==='statuses')renderStatusDonut(root,rows);else if(activityChart==='ranking')renderModelRanking(root,events);else renderTimeChart(root,series,activityChart);
 root.append(node('p','chart-source','Локальные наблюдения ProviderDock. Пустой период означает отсутствие данных, а не подтверждённую доступность.'));
 renderCompactProviderStates(id);
}
function renderTimeChart(root,series,kind){root.append(node('h3','',kind==='tokens'?'Расход токенов по дням':'Успешные и незавершённые попытки'));const values=series.map(bucket=>kind==='tokens'?bucket.tokens:bucket.attempts);const peak=Math.max(1,...values);const svg=svgNode('svg',{viewBox:'0 0 920 290',role:'img','aria-label':kind==='tokens'?'График расхода токенов':'График попыток запросов'});const w=800,h=200,left=78,top=20;for(let i=0;i<=4;i++){const y=top+h-i*h/4;svg.append(svgNode('line',{x1:left,y1:y,x2:left+w,y2:y,stroke:'#30343c'}));svgText(svg,left-12,y+4,fmtNum(Math.round(peak*i/4)),{'text-anchor':'end'})}const x=index=>left+(index+.5)*w/series.length;const y=value=>top+h-value/peak*h;
 if(kind==='tokens'){const path=svgNode('polyline',{points:values.map((value,index)=>x(index)+','+y(value)).join(' '),fill:'none',stroke:'#8caeff','stroke-width':2.5});svg.append(path)}
 series.forEach((bucket,index)=>{const label=bucket.date+' · '+fmtNum(values[index])+(kind==='tokens'?' токенов':' попыток');if(kind==='tokens'){const point=svgNode('circle',{cx:x(index),cy:y(bucket.tokens),r:4,fill:'#8caeff',tabindex:0});chartHint(point,label);svg.append(point)}else{const width=Math.min(45,w/series.length*.65);for(const [value,offset,color] of [[bucket.ok,0,'#53ba91'],[bucket.failed,bucket.ok,'#e57079']]){const rect=svgNode('rect',{x:x(index)-width/2,y:y(value+offset),width,height:Math.max(0,value/peak*h),rx:2,fill:color,tabindex:0});chartHint(rect,label+' · '+bucket.ok+' успешно · '+bucket.failed+' незавершённых / ошибок');svg.append(rect)}}if(series.length<=7||index%5===0||index===series.length-1)svgText(svg,x(index),250,bucket.date.slice(8)+'.'+bucket.date.slice(5,7),{'text-anchor':'middle'})});root.append(svg);if(!values.some(Boolean))root.append(node('p','empty','За этот период сохранённых данных нет.'));if(kind==='requests')root.append(node('p','hint','Зелёный — завершён · красный — ошибка или неполный ответ'));
}
function renderStatusDonut(root,rows){root.append(node('h3','','Текущее состояние моделей'));const counts=new Map();for(const row of rows)counts.set(row.status,(counts.get(row.status)||0)+1);const wrap=node('div','donut-layout');const svg=svgNode('svg',{viewBox:'0 0 300 250',role:'img','aria-label':'Текущие состояния '+rows.length+' моделей'});const circle=2*Math.PI*82;let offset=0;svg.append(svgNode('circle',{cx:150,cy:120,r:82,fill:'none',stroke:'#30343c','stroke-width':25}));const legend=node('div','chart-legend');for(const [status,count] of counts){const arc=svgNode('circle',{cx:150,cy:120,r:82,fill:'none',stroke:healthColors[status]||healthColors.UNKNOWN,'stroke-width':25,'stroke-dasharray':(count/rows.length*circle)+' '+circle,'stroke-dashoffset':-offset,transform:'rotate(-90 150 120)',tabindex:0});chartHint(arc,(statusLabels[status]||status)+': '+count);svg.append(arc);offset+=count/rows.length*circle;const item=node('span');const dot=node('i');dot.style.background=healthColors[status]||healthColors.UNKNOWN;item.append(dot,document.createTextNode((statusLabels[status]||status)+' · '+fmtNum(count)));legend.append(item)}svgText(svg,150,124,fmtNum(rows.length),{'text-anchor':'middle','font-size':28,fill:'#eef0f5'});svgText(svg,150,147,'моделей',{'text-anchor':'middle'});wrap.append(svg,legend);root.append(wrap)}
function renderModelRanking(root,events){root.append(node('h3','','Использование моделей · топ 10'));const counts=new Map();for(const event of events){const key=JSON.stringify([event.providerId,event.modelId]);counts.set(key,(counts.get(key)||0)+1)}const sorted=[...counts].sort((a,b)=>b[1]-a[1]);const max=sorted[0]?.[1]||1;for(const [key,count] of sorted.slice(0,10)){const [providerId,modelId]=JSON.parse(key);const line=node('button','ranking-row');line.type='button';line.append(node('span','',(providerById(providerId)?.displayName||providerId)+' / '+modelId));const meter=node('meter');meter.min=0;meter.max=max;meter.value=count;line.append(meter,node('b','',count+' запросов'));line.addEventListener('click',()=>{const row=allModelRows().find(row=>row.providerId===providerId&&row.modelId===modelId);if(row)openModelDetails(row)});root.append(line)}if(!sorted.length)root.append(node('p','empty','Данных по запросам пока нет.'))}
function renderCompactProviderStates(selected){const root=byId('activity-provider-models');root.replaceChildren();for(const profile of state.snapshot?.providers||[]){if(selected&&profile.id!==selected)continue;const rows=modelRows(profile.id);const section=node('details','provider-health-summary');section.open=activityExpanded.has(profile.id);const summary=node('summary');const title=node('strong','',profile.displayName);const counts=new Map();for(const row of rows)counts.set(row.status,(counts.get(row.status)||0)+1);const strip=node('span','status-distribution');strip.setAttribute('aria-label',rows.length+' моделей');for(const [status,count] of counts){const part=node('span');part.style.flexGrow=count;part.style.background=healthColors[status]||healthColors.UNKNOWN;part.title=(statusLabels[status]||status)+': '+count;strip.append(part)}summary.append(title,node('span','hint',fmtNum(rows.length)+' моделей'),strip);section.append(summary);const detail=node('div','provider-health-detail');section.append(detail);section.addEventListener('toggle',()=>{if(section.open){activityExpanded.add(profile.id);renderProviderModelHistory(detail,profile)}else{activityExpanded.delete(profile.id);detail.replaceChildren()}});if(section.open)renderProviderModelHistory(detail,profile);root.append(section)}}
function renderProviderModelHistory(root,profile){root.replaceChildren();const query=activitySearch[profile.id]||'';const search=node('input');search.type='search';search.placeholder='Найти модель';search.value=query;search.setAttribute('aria-label','Модель у '+profile.displayName);search.addEventListener('input',()=>{activitySearch[profile.id]=search.value;activityPages[profile.id]=0;renderProviderModelHistory(root,profile);const input=root.querySelector('input');input.focus()});root.append(search);const rows=modelRows(profile.id).filter(row=>row.modelId.toLowerCase().includes(query.toLowerCase()));const page=Math.min(activityPages[profile.id]||0,Math.max(0,Math.ceil(rows.length/20)-1));activityPages[profile.id]=page;const signals=healthMap().get(profile.id)?.runtimeSignals||[];const current=Date.now();for(const row of rows.slice(page*20,page*20+20)){const item=node('button','model-health-row');item.type='button';const head=node('div','model-health-head');head.append(node('strong','',row.modelId),badge(row.status));const recent=signals.filter(signal=>signal.modelId===row.modelId&&Date.parse(signal.observedAt)>current-86400000&&Date.parse(signal.observedAt)<=current);const ok=recent.filter(signal=>signal.outcome==='completed').length;head.append(node('span','hint',recent.length?new Intl.NumberFormat('ru-RU',{maximumFractionDigits:1}).format(ok/recent.length*100)+'% · '+recent.length+' попыток':'Нет трафика'));const protocol=[...new Set(recent.map(signal=>signal.protocol))];if(protocol.length)head.append(node('small','hint',protocol.join(' · ')));const timeline=node('div','model-health-timeline');for(let index=0;index<24;index++){const begin=current-(24-index)*3600000;const samples=recent.filter(signal=>Date.parse(signal.observedAt)>begin&&Date.parse(signal.observedAt)<=begin+3600000);const status=samples.length?(samples.every(signal=>signal.outcome==='completed')?'ONLINE':samples.some(signal=>signal.outcome==='completed')?'DEGRADED':'OFFLINE'):'UNKNOWN';const cell=node('span');cell.style.background=healthColors[status];cell.title=new Intl.DateTimeFormat('ru-RU',{hour:'2-digit',minute:'2-digit'}).format(new Date(begin))+' · '+(samples.length?samples.length+' попыток · '+(statusLabels[status]||status):'нет наблюдений');timeline.append(cell)}item.append(head,timeline);item.addEventListener('click',()=>openModelDetails(row));root.append(item)}const controls=node('div','history-pagination');const previous=miniButton('Назад','',()=>{activityPages[profile.id]=page-1;renderProviderModelHistory(root,profile)});previous.disabled=page===0;const next=miniButton('Далее','',()=>{activityPages[profile.id]=page+1;renderProviderModelHistory(root,profile)});next.disabled=(page+1)*20>=rows.length;controls.append(previous,node('span','hint',(page+1)+' / '+Math.max(1,Math.ceil(rows.length/20))+' · по 20 моделей'),next);root.append(controls)}
`;
