/** Small DOM-only catalog, shared by the card and table views. */
export const catalogJavaScript = `
let storefrontPage=0;
let storefrontView='cards';
const pageNames={providers:['Провайдеры','Подключения, баланс и состояние API.'],models:['Витрина моделей','Сравнивайте цены и выбирайте модель для своей задачи.'],launch:['Запуск агента','Выберите проект и маршрут для Codex CLI или Claude Code.'],routes:['Маршруты и профили','Резервные модели, инструкции и настройки проектов.'],activity:['Активность','Запуски и расходы по запросам через ProviderDock.'],settings:['Ключи и настройки','Локальное хранилище ключей и сессий кабинетов.']};
function setPage(page){if(!pageNames[page])page='providers';state.page=page;document.body.dataset.currentPage=page;for(const section of document.querySelectorAll('[data-page]'))section.hidden=section.dataset.page!==page;for(const button of document.querySelectorAll('[data-nav]')){button.classList.toggle('active',button.dataset.nav===page);if(button.dataset.nav===page)button.setAttribute('aria-current','page');else button.removeAttribute('aria-current')}byId('page-title').textContent=pageNames[page][0];byId('page-description').textContent=pageNames[page][1];history.replaceState(null,'','#'+page);window.scrollTo({top:0})}
function openStorefront(providerId=''){if(state.providerId)closeProvider();byId('model-provider').value=providerId;byId('model-group').value='';byId('model-search').value='';storefrontPage=0;setPage('models');renderModels()}
function priceNumber(value){return value==null?'—':value>0&&value<0.000001?value.toExponential(2).replace('.',','):new Intl.NumberFormat('ru-RU',{maximumFractionDigits:6}).format(value)}

function selectedTariff(){try{return JSON.parse(byId('model-group').value||'null')}catch{return null}}
function rowGroup(row){const selected=selectedTariff();return selected?.[0]===row.providerId?row.siteModel?.groups.find(group=>group.name===selected[1]):null}
function rowPrices(row){const group=rowGroup(row);return group?group.prices:row.siteModel?row.siteModel.basePrices:row.pricing}
function priceText(value,currency){return value==null?'—':priceNumber(value)+' '+currency}
function requestOnly(row){const prices=rowPrices(row);return row.siteModel?.billing==='request'||(prices?.perRequest!=null&&['inputPerMillion','outputPerMillion','cacheReadInputPerMillion'].every(key=>prices[key]==null))}
function tariffCaption(row){const group=rowGroup(row);return (group?group.name+(group.multiplier==null?'':' × '+priceNumber(group.multiplier)):row.siteModel?'Базовый тариф':row.pricing?'Ручной тариф':'Тариф не загружен')+(row.siteCatalog?.stale?' · устарело':'')}
function sourceLink(url,label){const link=node('a','link-button',label);link.href=url;link.target='_blank';link.rel='noopener noreferrer';return link}
function providerStatusClass(status){return status==='ONLINE'?'status-stable':['DEGRADED','RATE_LIMITED'].includes(status)?'status-limited':['OFFLINE','AUTH_ERROR','INCOMPATIBLE'].includes(status)?'status-unavailable':'status-unknown'}
function isUnavailable(status){return ['OFFLINE','AUTH_ERROR','RATE_LIMITED','INCOMPATIBLE','DEGRADED'].includes(status)}
function availabilityLabel(status){return {OFFLINE:'Временно недоступен',AUTH_ERROR:'Нет доступа · проверьте ключ',RATE_LIMITED:'Временно ограничен',INCOMPATIBLE:'Модель недоступна',DEGRADED:'Работает с ограничениями'}[status]||statusLabels[status]||'Не проверен'}
function removedCountdown(row){if(!row.removedAt)return 'Убрана из API · ожидает обновления';const left=Math.max(0,Date.parse(row.removedAt)+48*3600000-Date.now());const minutes=Math.ceil(left/60000);return left?'Убрана из API · исчезнет через '+Math.floor(minutes/60)+' ч '+minutes%60+' мин':'Срок хранения истёк · обновление…'}
function lifecycleLabel(row){return row.locallyDisabled?'Отключена вами':row.lifecycle==='removed'?removedCountdown(row):row.lifecycle==='site-hidden'?'Есть в API · скрыта на витрине':row.availabilityReason||''}
function renderStorefrontScope(){const root=byId('storefront-scope');root.replaceChildren();const profile=providerById(byId('model-provider').value);root.hidden=!profile;if(!profile)return;const portal=portalById(profile.id);const catalog=portal?.latest?.catalog;root.append(node('span','hint',catalog?.value?'Цены обновлены '+fmtWhen(catalog.observedAt)+(portalStale(catalog)?' · устарело':''):portal?'Цены: '+portalProblem(catalog):'Подключите сайт в настройках кабинета для загрузки цен.'));root.append(miniButton(portal?'↻ Обновить цены':'Настройки','quiet',()=>portal?refreshPortal(profile.id):openPortalDialog(profile.id)))}
function renderModels(){
 const root=byId('models');root.replaceChildren();const select=byId('model-provider');const old=select.value;
 select.replaceChildren(option('','Все провайдеры'));for(const profile of state.snapshot?.providers||[])select.append(option(profile.id,profile.displayName));select.value=providerById(old)?old:'';
 const scoped=allModelRows().filter(row=>!select.value||row.providerId===select.value);
 const groups=byId('model-group');const oldGroup=groups.value;groups.replaceChildren(option('','Базовые цены'));
 for(const profile of state.snapshot?.providers||[]){const names=[...new Set(scoped.filter(row=>row.providerId===profile.id).flatMap(row=>row.siteModel?.groups.map(group=>group.name)||[]))].sort();if(!names.length)continue;const group=node('optgroup');group.label=profile.displayName;for(const name of names)group.append(option(JSON.stringify([profile.id,name]),profile.displayName+' / '+name));groups.append(group)}
 groups.value=[...groups.options].some(item=>item.value===oldGroup)?oldGroup:'';groups.disabled=groups.options.length===1;
 const query=byId('model-search').value.trim().toLowerCase();const tariff=selectedTariff();
 const rows=scoped.filter(row=>!row.locallyDisabled&&(!query||[row.modelId,row.displayName,row.providerName,row.siteModel?.vendor,row.siteModel?.tags].join(' ').toLowerCase().includes(query))&&(!tariff||row.providerId===tariff[0]&&row.siteModel?.groups.some(group=>group.name===tariff[1]))).sort((a,b)=>a.providerName.localeCompare(b.providerName)||a.modelId.localeCompare(b.modelId));
 const pages=Math.max(1,Math.ceil(rows.length/50));storefrontPage=Math.min(storefrontPage,pages-1);byId('model-count').textContent=rows.length+' моделей';byId('model-page').textContent=(storefrontPage+1)+' / '+pages;byId('models-prev').disabled=storefrontPage===0;byId('models-next').disabled=storefrontPage===pages-1;byId('model-results-note').textContent=rows.length+' моделей · цены за 1 миллион токенов или за запрос';renderStorefrontScope();
 for(const button of document.querySelectorAll('[data-model-view]')){button.classList.toggle('active',button.dataset.modelView===storefrontView);button.setAttribute('aria-pressed',String(button.dataset.modelView===storefrontView))}
 if(!rows.length)root.append(node('p','empty','Модели не найдены. Измените фильтры или включите модели в настройках провайдера.'));
 const visible=rows.slice(storefrontPage*50,(storefrontPage+1)*50);
 for(const providerId of new Set(visible.map(row=>row.providerId))){const profile=providerById(providerId);const section=node('section','catalog-provider');section.dataset.catalogProvider=providerId;const heading=node('div','catalog-provider-head');heading.append(node('h2','',profile.displayName),node('span','hint',rows.filter(row=>row.providerId===providerId).length+' моделей'),miniButton('Настройки','quiet',()=>openProviderDialog(profile)));section.append(heading);
 const list=visible.filter(row=>row.providerId===providerId);if(storefrontView==='table')section.append(createModelTable(list));else{const grid=node('div','storefront-grid');for(const row of list)grid.append(createModelCard(row));section.append(grid)}root.append(section)}
}
function modelSection(row){return row.lifecycle==='removed'||['OFFLINE','AUTH_ERROR','INCOMPATIBLE','DISABLED'].includes(row.status)?'unavailable':row.lifecycle==='site-hidden'?'site-hidden':row.lifecycle==='unverified'&&row.status!=='ONLINE'?'unverified':'available'}
function appendPrices(root,row,prices=rowPrices(row)){if(!requestOnly(row)){const grid=node('div','price-grid');for(const [field,label] of [['inputPerMillion','Вход'],['outputPerMillion','Выход'],['cacheReadInputPerMillion','Кэш']]){const cell=node('div');cell.append(node('small','',label),node('strong','',priceText(prices?.[field],prices?.currency)));grid.append(cell)}root.append(grid)}if(requestOnly(row)||prices?.perRequest!=null)root.append(node('p','request-price',priceText(prices?.perRequest,prices?.currency)+' / запрос'))}
function createModelCard(row){const card=node('article','model-card '+providerStatusClass(row.status));card.dataset.modelId=row.modelId;card.classList.toggle('unavailable',isUnavailable(row.status));const heading=node('div','model-card-heading');const identity=node('div','model-identity');identity.append(node('span','model-provider-name',row.providerName),node('h3','',row.modelId));heading.append(identity,node('span','model-open','↗'));card.append(heading);appendPrices(card,row);card.append(node('p','model-description',row.siteModel?.description||'Описание отсутствует.'));const footer=node('div','model-card-footer');footer.append(node('span','tariff-caption',tariffCaption(row)));const metrics=node('div','model-perf');metrics.append(node('span','','Задержка '+modelLatency(row)),badge(row.status));footer.append(metrics);const lifecycle=lifecycleLabel(row);if(lifecycle)footer.append(node('span',row.lifecycle==='site-hidden'?'site-hidden-note':'availability-alert',lifecycle));const launch=miniButton('Запустить','model-quick-launch',()=>selectModelForLaunch(row.providerId,row.modelId));launch.disabled=!row.enabled||row.lifecycle==='removed';footer.append(launch);card.append(footer);bindModelCard(card,row);return card}
function createModelTable(rows){const scroll=node('div','table-scroll');const table=node('table');const head=node('tr');for(const label of ['Провайдер / модель','Цена / 1M или запрос','Тарифная группа','Задержка','Состояние'])head.append(node('th','',label));const thead=node('thead');thead.append(head);table.append(thead);const tbody=node('tbody');for(const row of rows){const tr=node('tr','model-table-row'+(isUnavailable(row.status)||row.lifecycle==='removed'?' unavailable':''));const name=node('td');name.append(node('span','model-sub',row.providerName),node('span','model-id',row.modelId));const prices=node('td');appendPrices(prices,row);tr.append(name,prices,wrapCell(tariffCaption(row)),wrapCell(modelLatency(row)),wrapCell(lifecycleLabel(row)||badge(row.status)));bindModelCard(tr,row);tbody.append(tr)}table.append(tbody);scroll.append(table);return scroll}
function modelLatency(row){return row.sitePerformance?.latencyMs!=null?priceNumber(row.sitePerformance.latencyMs/1000)+' с'+(row.sitePerformance.stale?' · устарело':''):'—'}
function bindModelCard(card,row){card.tabIndex=0;card.setAttribute('role','button');card.setAttribute('aria-label',row.providerName+' · '+row.modelId+' · открыть сведения');card.setAttribute('aria-haspopup','dialog');card.addEventListener('click',event=>{if(!event.target.closest('button,a'))openModelDetails(row)});card.addEventListener('keydown',event=>{if(event.target===card&&(event.key==='Enter'||event.key===' ')){event.preventDefault();openModelDetails(row)}})}
function setSettingsTab(tab){for(const button of document.querySelectorAll('[data-settings-tab]')){const active=button.dataset.settingsTab===tab;button.classList.toggle('active',active);button.setAttribute('aria-selected',String(active))}byId('provider-form').hidden=tab!=='provider';byId('portal-form').hidden=tab!=='account'}
function renderDisabledModels(root,profile){root.querySelector('.disabled-models')?.remove();if(!profile)return;const ids=profile.disabledModelIds||[];if(!ids.length)return;const details=node('details','disabled-models');details.append(node('summary','','Отключены вами · '+ids.length));for(const modelId of ids){const line=node('div','disabled-model-row');line.append(node('span','model-id',modelId),miniButton('Включить','',()=>setModelEnabled(profile.id,modelId,true)));details.append(line)}root.append(details)}
async function setModelEnabled(providerId,modelId,enabled){try{await api('api/providers/'+encodeURIComponent(providerId)+'/model-state',{method:'PUT',body:JSON.stringify({modelId,enabled})});if(byId('model-detail-dialog').open)byId('model-detail-dialog').close();await refresh();if(state.editingProvider?.id===providerId)renderDisabledModels(byId('provider-model-controls'),providerById(providerId));setStatus(globalStatus(),'ok',enabled?'Модель включена.':'Модель отключена. Вернуть её можно в настройках провайдера.')}catch(error){const target=byId('model-detail-dialog').open?'model-test-status':globalStatus();setStatus(target,'err',error.message)}}
function renderUsageCosts(usage){const totals={};const root=byId('usage-cost-breakdown');root.replaceChildren();for(const row of usage){const costs=Object.entries(row.costs||{});for(const [currency,amount] of costs)totals[currency]=(totals[currency]||0)+amount;if(costs.length)root.append(node('span','cost-item',(providerById(row.providerId)?.displayName||row.providerId)+' / '+row.modelId+' · '+fmtCost(row.costs)))}byId('usage-cost-total').textContent=Object.keys(totals).length?fmtCost(totals):'Нет оценки';if(!root.childElementCount)root.append(node('p','hint','Расчёт появится после запросов с настроенной стоимостью токенов.'))}
`;
