import { catalogJavaScript } from "./provider-dashboard-catalog.js";
export const storefrontJavaScript = `
${catalogJavaScript}
function openModelDetails(row){
 const body=byId('model-detail-body');body.replaceChildren();byId('model-detail-title').textContent=row.modelId;const model=row.siteModel;const perf=row.sitePerformance;
 body.append(node('p','model-provider-name',row.providerName+' · '+(requestOnly(row)?'За запрос':'За 1M токенов')),node('p','model-description',model?.description||'Описание отсутствует.'));const lifecycle=lifecycleLabel(row);if(lifecycle)body.append(node('p',row.lifecycle==='site-hidden'?'site-hidden-note':'availability-alert',lifecycle));
 const tabs=node('div','model-detail-tabs');tabs.setAttribute('role','tablist');tabs.setAttribute('aria-label','Сведения о модели');const panes={};
 for(const [id,label] of [['overview','Обзор'],['performance','Производительность'],['api','API']]){const button=miniButton(label,'',()=>{for(const [key,pane] of Object.entries(panes))pane.hidden=key!==id;for(const item of tabs.children){item.classList.toggle('active',item===button);item.setAttribute('aria-selected',String(item===button))}});button.dataset.detailTab=id;button.id='detail-tab-'+id;button.setAttribute('role','tab');button.setAttribute('aria-controls','detail-pane-'+id);button.setAttribute('aria-selected',String(id==='overview'));button.classList.toggle('active',id==='overview');tabs.append(button);const pane=node('section','model-detail-pane');pane.id='detail-pane-'+id;pane.setAttribute('role','tabpanel');pane.setAttribute('aria-labelledby',button.id);pane.hidden=id!=='overview';panes[id]=pane}body.append(tabs,...Object.values(panes));
 const overview=panes.overview;const metrics=node('div','model-detail-metrics');metrics.append(statCell('TPS',perf?.tokensPerSecond==null?'—':priceNumber(perf.tokensPerSecond)+' ток/с','по данным сайта'),statCell('Средняя задержка',modelLatency(row),'по данным сайта'),statCell('Успешные запросы',perf?.successRatePct==null?'—':priceNumber(perf.successRatePct)+'%','за 24 часа'));overview.append(metrics);
 const pricing=node('section','detail-box');pricing.append(node('h3','','Ценообразование'),node('h4','','Базовая цена'));appendPrices(pricing,row,model?.basePrices||row.pricing);
 if(model?.groups.length){pricing.append(node('h4','','Цены по группам · '+row.providerName));const scroll=node('div','table-scroll');const table=node('table');const head=node('tr');const fields=requestOnly(row)?[['perRequest','За запрос']]:[['inputPerMillion','Вход'],['outputPerMillion','Выход'],['cacheReadInputPerMillion','Кэш']];if(!requestOnly(row)&&model.groups.some(group=>group.prices?.perRequest!=null))fields.push(['perRequest','За запрос']);for(const label of ['Группа','Коэффициент',...fields.map(field=>field[1])])head.append(node('th','',label));const thead=node('thead');thead.append(head);table.append(thead);const tbody=node('tbody');for(const group of model.groups){const tr=node('tr');tr.append(wrapCell(group.name),wrapCell(group.multiplier==null?'—':priceNumber(group.multiplier)+'×'));for(const [field] of fields)tr.append(wrapCell(priceText(group.prices?.[field],group.prices?.currency)));tbody.append(tr)}table.append(tbody);scroll.append(table);pricing.append(scroll)}pricing.append(node('p','hint',requestOnly(row)?'Стоимость за один запрос.':'Цены за 1 миллион токенов. Коэффициенты групп учтены в таблице.'));if(row.siteCatalog)pricing.append(sourceLink(row.siteCatalog.sourceUrl,'Источник тарифов ↗'),node('span','hint',' '+fmtWhen(row.siteCatalog.observedAt)+(row.siteCatalog.stale?' · устарело':'')));overview.append(pricing);
 const info=node('section','detail-box');info.append(node('h3','','Модель'));const kv=node('div','kv-grid');kv.append(kvItem('Провайдер',row.providerName),kvItem('Тип оплаты',requestOnly(row)?'За запрос':model?.billing==='dynamic'?'Динамический':'За токены'),kvItem('Группы',model?.groups.map(group=>group.name).join(', ')||'Нет данных'),kvItem('Состояние',availabilityLabel(row.status)));info.append(kv);overview.append(info);
 panes.performance.append(node('h3','','Статистика сайта'),node('p','',perf?priceNumber(perf.tokensPerSecond)+' ток/с · '+modelLatency(row)+' · '+priceNumber(perf.successRatePct)+'% успешных запросов'+(perf.stale?' · данные устарели':''):'Данные сайта отсутствуют.'),node('h3','','Ваши запросы'),node('p','',row.total?row.ok+' успешно · '+row.err+' ошибок · '+row.rateLimited+' ответов 429':'Запросов через ProviderDock пока нет.'));if(perf)panes.performance.append(sourceLink(perf.sourceUrl,'Источник статистики ↗'),node('p','hint',fmtWhen(perf.observedAt)));
 panes.api.append(node('h3','','Подключение'),kvItem('Провайдер',row.providerName),kvItem('Модель',row.modelId,'mono'),kvItem('Base URL',providerById(row.providerId)?.baseUrl||'—','mono'),kvItem('Конечные точки',model?.endpointTypes.join(', ')||'Нет данных'),kvItem('Контекст',model?.contextTokens?fmtNum(model.contextTokens)+' токенов':'Нет данных'),node('p','hint','Список API проверен: '+fmtWhen(row.catalogCheckedAt)));
 const actions=node('div','model-detail-actions');const test=miniButton('Тест модели','',()=>doctorProvider(row.providerId,3,byId('model-test-status'),test,row.modelId));test.disabled=!row.enabled;const launch=miniButton('В запуск','active',()=>{byId('model-detail-dialog').close();selectModelForLaunch(row.providerId,row.modelId)});launch.disabled=!row.enabled||row.lifecycle==='removed';actions.append(miniButton('Ручной тариф','quiet',()=>openPricingDialog(row)),test,launch,miniButton(row.locallyDisabled?'Включить модель':'Отключить модель',row.locallyDisabled?'':'danger',()=>setModelEnabled(row.providerId,row.modelId,Boolean(row.locallyDisabled))));body.append(actions,node('p','hint','Тест отправляет до 5 запросов генерации и расходует токены.'));const status=node('div','status-line');status.id='model-test-status';body.append(status);if(!byId('model-detail-dialog').open)byId('model-detail-dialog').showModal();
}
`;
