import { z } from "zod";
import type { ProviderProfile } from "../../core/providers/provider-profile.js";
import type { SecretStore } from "../../core/security/secret-store.js";

const modelIdSchema = z.string().trim().min(1).max(256);
const sessionIdSchema = z.string().regex(/^[a-f0-9]{32}$/);

export type CodexProviderRoute =
  | { readonly kind: "direct" }
  | { readonly kind: "bridge"; readonly baseUrl: string };

export type CodexLaunchRoute = CodexProviderRoute | { readonly kind: "auto" };

export interface BuildCodexRuntimeConfigInput {
  readonly profile: ProviderProfile;
  readonly modelId: string;
  readonly route: CodexProviderRoute;
  readonly sessionId: string;
}

export interface BuiltCodexRuntimeConfig {
  readonly profileName: string;
  readonly providerName: string;
  readonly contents: string;
  readonly environment: Readonly<Record<string, string>>;
}

export class CodexRuntimeConfigurationError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "CodexRuntimeConfigurationError";
  }
}

export class CodexRuntimeConfigFactory {
  constructor(private readonly secrets: SecretStore) {}

  async build(input: BuildCodexRuntimeConfigInput): Promise<BuiltCodexRuntimeConfig> {
    const modelId = modelIdSchema.parse(input.modelId);
    const sessionId = sessionIdSchema.parse(input.sessionId);
    const profileName = `providerdock-${sessionId}`;
    const providerName = profileName;
    const direct = input.route.kind === "direct";

    if (
      direct &&
      !["auto", "openai-responses"].includes(input.profile.apiType)
    ) {
      throw new CodexRuntimeConfigurationError(
        `Provider '${input.profile.id}' requires a compatibility bridge for Codex because its API type is '${input.profile.apiType}'.`,
      );
    }
    if (direct && input.profile.auth.kind === "query") {
      throw new CodexRuntimeConfigurationError(
        "Codex direct mode cannot inject a secret query parameter; use the compatibility bridge.",
      );
    }
    if (direct && Object.keys(input.profile.queryParameters).length > 0) {
      throw new CodexRuntimeConfigurationError(
        "Codex direct mode does not safely support provider query parameters; use the compatibility bridge.",
      );
    }

    const baseUrl = direct ? input.profile.baseUrl : validateHttpUrl(input.route.baseUrl);
    const environment: Record<string, string> = {};
    const envHeaders = new Map<string, { readonly name: string; readonly envName: string }>();
    let environmentIndex = 0;
    const addEnvironmentValue = (label: string, value: string): string => {
      const normalizedLabel = label.toUpperCase().replace(/[^A-Z0-9]+/g, "_").replace(/^_+|_+$/g, "");
      const envName = `PROVIDER_DOCK_CODEX_${sessionId.toUpperCase()}_${environmentIndex++}_${normalizedLabel || "VALUE"}`;
      environment[envName] = value;
      return envName;
    };
    const addHeader = (name: string, value: string) => {
      envHeaders.set(name.toLowerCase(), {
        name,
        envName: addEnvironmentValue(`HEADER_${name}`, value),
      });
    };

    let envKey: string | undefined;
    if (direct) {
      for (const [name, value] of Object.entries(input.profile.staticHeaders)) {
        addHeader(name, value);
      }

      if (input.profile.auth.kind === "bearer") {
        envKey = addEnvironmentValue(
          "API_KEY",
          await this.requireSecret(input.profile.auth.secretRef),
        );
      } else if (input.profile.auth.kind === "header") {
        addHeader(
          input.profile.auth.headerName,
          await this.requireSecret(input.profile.auth.secretRef),
        );
      }

      for (const [name, reference] of Object.entries(input.profile.secretHeaders)) {
        addHeader(name, await this.requireSecret(reference));
      }
    }

    const lines = [
      "# Generated by ProviderDock for one runtime session. Do not edit.",
      `model = ${tomlString(modelId)}`,
      `model_provider = ${tomlString(providerName)}`,
      "",
      `[model_providers.${tomlString(providerName)}]`,
      `name = ${tomlString(direct ? input.profile.displayName : `${input.profile.displayName} via ProviderDock Bridge`)}`,
      `base_url = ${tomlString(baseUrl)}`,
      'wire_api = "responses"',
      "request_max_retries = 0",
      "stream_max_retries = 0",
    ];
    if (envKey) lines.push(`env_key = ${tomlString(envKey)}`);
    if (envHeaders.size > 0) {
      lines.push(
        `env_http_headers = ${tomlInlineTable(
          [...envHeaders.values()].map(({ name, envName }) => [name, envName]),
        )}`,
      );
    }
    lines.push("");

    return { profileName, providerName, contents: lines.join("\n"), environment };
  }

  private async requireSecret(reference: string): Promise<string> {
    const secret = await this.secrets.get(reference);
    if (!secret) {
      throw new CodexRuntimeConfigurationError(
        `Required secret reference '${reference}' is not available.`,
      );
    }
    return secret;
  }
}

function validateHttpUrl(value: string): string {
  const parsed = z.string().url().parse(value);
  if (!parsed.startsWith("http://") && !parsed.startsWith("https://")) {
    throw new CodexRuntimeConfigurationError("Codex provider URL must use HTTP or HTTPS.");
  }
  return parsed.replace(/\/+$/, "");
}

function tomlString(value: string): string {
  return JSON.stringify(value);
}

function tomlInlineTable(entries: readonly (readonly [string, string])[]): string {
  return `{ ${[...entries]
    .sort(([left], [right]) => left.localeCompare(right))
    .map(([key, value]) => `${tomlString(key)} = ${tomlString(value)}`)
    .join(", ")} }`;
}
